### ISSUE TITLE
Add more categories/genres in Spanish

### ISSUE THREAD

**Issue by Franqsanz** [Franqsanz/xbu#2]
There are many categories/genres of books to add, the only condition to this is that they are in Spanish, add it to the file and in the [array](https://github.com/Franqsanz/xbu/blob/main/src/data/links.ts#L71C1-L114C3), field must be the same for example: `{ value: 'Aventura', label: 'Aventura' }`

**Comment by Asish-AP** [comment]
Hey @Franqsanz is this issue fixed/closed?

**Comment by Franqsanz** [comment]
You can still contribute, but check carefully that no genre is repeated and check the commits when making one, I had problems with the last contributor. Thanks for your interest!
